apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-deployment
  labels:
    app: crud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crud
  template:
    metadata:
      labels:
        app: crud
    spec:
      containers:
      - name: crud
        image: crud-app-arm:5fa3c07d652944a641acf9ad35738ba46d229224 charan1924/crud-app-arm:latest 
        ports:
        - containerPort: 8000
