apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-deployment
  labels:
    app: crud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crud
  template:
    metadata:
      labels:
        app: crud
    spec:
      containers:
      - name: crud
        image: crud-app-arm:e5fef72b427ffdc7dd3fb3621de4d9de90ce3371
        ports:
        - containerPort: 8000
